### ISSUE TITLE
serializable properties should have unique ids

### ISSUE THREAD

**Issue by kmkolasinski** [lexxmark/QtnProperty#12]
Hi, at first I would like to thank you for all the help you done to integrate Qtn in AwesomeBump project. I slowly introduce changes in GUI and everything works perfect. 
However today I've tried to implement saving feature which is done in following way. I have multiple propertysets which are separate, but I want to keep all the data in one file. So to do that I decided to make another property set which I will use to keep all the data in one place:
```
property_set AwesomeBump{
    extern property_set FormImageProp Diffuse{}
    extern property_set FormImageProp Specular{}
}
```
In future I'm going to add more properties to it. Then during save I do
```
    abSettings->Diffuse.copyValues(diffuseImageProp->imageProp.properties);
    abSettings->Specular.copyValues(specularImageProp->imageProp.properties);  
    QFile file( "test.dat" );
    QDataStream stream( &file );
    abSettings->save(stream);
```
Which causes this assert:

> ASSERT: "false && "serializable properties should have unique ids"" in file ../AwesomeBump/Sources/utils/QtnProperty/Core/PropertySet.cpp, line 332

However I tried to use: 
```
QTextStream stream(&file);
QString data;
abSettings->toStr(data);
stream << data;
```
But only the first property FormImageProp Diffuse was written into file. Do you know how to fix it?

**Comment by lexxmark** [comment]
Hi Krzysztof,
  Thank you for using QtnProperty in your project.

If you want to save several properties in one QDataStream you can save them by calling save(stream) method for each of them and controlling witch version saves/load which properties.
Another way is add all properties as sub-property sets to SUPER-property set, as you did but don't make copy of properties. Just add existing property sets like this:
```
    QtnPropertySet superPropertySet;
    superPropertySet.addChildProperty(diffuseImageProp->imageProp.properties, false /*don't move ownership*/);
    superPropertySet.addChildProperty(specularImageProp->imageProp.properties, false /*don't move ownership*/);
...
    QFile file( "test.dat" );
    QDataStream stream( &file );
    superPropertySet.save(stream);
```
ASSERT is raised because if you save properties in bin format they use id (not name) to identify themself among other properties. So you have to add unique id attribute to each property in *.pef files. Like:
```
property_set Filter3DBloom
{
    id = 1;
    Bool EnableEffect
    {
        id = 2;
        description = "EnableEffect";
        name      = "Enable Bloom";
        value     = true;
    }
    Float WeightA
    {
        id = 3;
        description = "Weight of Layer A.";
        name      = "Layer A";
        value     = 0.25f;
        minValue  = 0.0f;
        maxValue  = 1.0f;
        stepValue = 0.01f;
    }
...
```

It's not very convenient way but it works. Just assign unique id for every property and change id if you change property type (for example from Int to Float).

Also you can use superPropertySet.toStr(str) method and it should work. I will investigate this problem.

P.S. you can use ";" instead "{}" for external property sets  and delegates in *.pef files.

**Comment by kmkolasinski** [comment]
Hi, thanks for an answer I will try the first solution and give a feedback.

**Comment by kmkolasinski** [comment]
So, the first way leads to the same assert. Second one is very inconvenient and thus I would prefer to avoid it, since maybe some day I will want to add a new property in the middle, and I will have to look through all the file what ID choose to avoid duplicates. 
superPropertySet.toStr(str) - saves only one property set so instead of something like that:
```
Diffuse.ImageType = 9
Diffuse.GrungeOnImage.BlendingMode = BLENDINGMODE::Normal
Diffuse.GrungeOnImage.ImageWeight = 0.5
Diffuse.GrungeOnImage.GrungeWeight = 0
Specular.ImageType = 9
Specular.GrungeOnImage.BlendingMode = BLENDINGMODE::Normal
Specular.GrungeOnImage.ImageWeight = 0.5
Specular.GrungeOnImage.GrungeWeight = 0
```
I have only 
```
Diffuse.ImageType = 9
Diffuse.GrungeOnImage.BlendingMode = BLENDINGMODE::Normal
Diffuse.GrungeOnImage.ImageWeight = 0.5
Diffuse.GrungeOnImage.GrungeWeight = 0
```
Strange is that FormImageProp saves all the properties which has inside, I expected that when I put it to another property everything will be automatic.

**Comment by lexxmark** [comment]
Ok, I will try to reproduce problem with toStr() method.
You can help me by posting broken code (as temporary branch in AB project for example).

Also I'm thinking about implementing more well known text format. What do you prefer, XML or JSON?

**Comment by lexxmark** [comment]
I've added some diagnostics to debug console if load/save is unsuccessful.
Also I've found the problem - unimplemented saveStr/loadStr methods for Button property.
Please update your QtnProperty submodule to latest commit

**Comment by kmkolasinski** [comment]
Hi, so basically I use the same *.pef file as it is in current master: [ImageProperties](https://github.com/kmkolasinski/AwesomeBump/blob/master/Sources/properties/ImageProperties.pef#L895) 
What I did I added AwesomeBump property set:
```
property_set AwesomeBump{
    extern property_set FormImageProp Diffuse{}
    extern property_set FormImageProp Specular{}
}
```
And I was thinking to use it as global container for all properties in the project, not only for FormImageProp's. I can commit what I have but basically that is what I have managed to add since two weeks. It should reproduce all errors. Then I try to save AwesomeBump to file.

> Also I'm thinking about implementing more well known text format. What do you prefer, XML or JSON?

For me it does not play any role, however I like the current one because it is very compact, I expect XML files to be much larger. 

> I've added some diagnostics to debug console if load/save is unsuccessful.
Also I've found the problem - unimplemented saveStr/loadStr methods for Button property.
Please update your QtnProperty submodule to latest commit

Thanks, I will update it in the evening.

**Comment by kmkolasinski** [comment]
Hi, unfortunately I did not have time to check it, next week I will do it.

**Comment by lexxmark** [comment]
I've fixed **pef** files compilation and added **resetIcon** parameter to initQtnPropertyWidgetLibrary function.
I suggest to checkout last master commit.

**Comment by kmkolasinski** [comment]
Hi Alex, 
I think, I have pulled the last commit from your project, but it seems that saving still does not work :/ 
Still or only one sub-property is saved or I have error with unique values. Do you have some progress in this problem or do I really have to add ID for each property manually ?

**Comment by lexxmark** [comment]
Hi Krzysztof,

unfortunately you reference QtnProperty submodule to invalid commit. I had made a lot of dummy commits to enable TravisCI in my project. Then I merged these commits into the single one. It seems you refer to one these commits. Please update QtnProperty submodule again.

In QtnProperty master I've fixed the following functions:
```
    bool fromStr(const QString& str);
    bool toStr(QString& str) const;
```
Please try them.

**Comment by kmkolasinski** [comment]
Hi, thanks for the info, I will check it on days and will give you response.

**Comment by kmkolasinski** [comment]
Cool, it seems it works, I will test it in few days, and that will be probably all what I needed. 
Reset button is also nice, much better I remember it :+1: 
Once more thanks for feedback.

**Comment by lexxmark** [comment]
You are welcome.

**Comment by kmkolasinski** [comment]
Hi Alex,
I did the update but it seems that there are still problems. I've managed to make it save correctly to file with toStr function. I have a code which saves all properties in the following way:
    

    abSettings->Diffuse  .copyValues(diffuseImageProp   ->imageProp.properties);
    abSettings->Specular .copyValues(specularImageProp  ->imageProp.properties);
    abSettings->Normal   .copyValues(normalImageProp    ->imageProp.properties);
    abSettings->Occlusion.copyValues(occlusionImageProp ->imageProp.properties);
    abSettings->Height   .copyValues(heightImageProp    ->imageProp.properties);
    abSettings->Metallic .copyValues(metallicImageProp  ->imageProp.properties);
    abSettings->Roughness.copyValues(roughnessImageProp ->imageProp.properties);
    abSettings->Grunge   .copyValues(grungeImageProp    ->imageProp.properties);

    QFile file( QString(AB_INI) );
    QTextStream stream(&file);
    QString data;
    abSettings->toStr(data);
    stream << data;

And trying to load same properties with following code:

    QFile file( QString(AB_INI) );
    QTextStream stream(&file);
    QString data;
    stream >> data;
    abSettings->fromStr(data);

    diffuseImageProp    ->imageProp.properties->copyValues(&abSettings->Diffuse);
    specularImageProp   ->imageProp.properties->copyValues(&abSettings->Specular);
    normalImageProp     ->imageProp.properties->copyValues(&abSettings->Normal);
    occlusionImageProp  ->imageProp.properties->copyValues(&abSettings->Occlusion);
    heightImageProp     ->imageProp.properties->copyValues(&abSettings->Height);
    metallicImageProp   ->imageProp.properties->copyValues(&abSettings->Metallic);
    roughnessImageProp  ->imageProp.properties->copyValues(&abSettings->Roughness);
    grungeImageProp     ->imageProp.properties->copyValues(&abSettings->Grunge);

But if I change something in the AB_INI file it does not work for some reason. Instead I get error:
`Cannot parse string: " "presetName" "`,
but in the AB_INI file there is such property, here is first few lines of this file:

    presetName = Default 
    Diffuse.ImageType = 9
    Diffuse.GrungeOnImage.BlendingMode = BLENDINGMODE::Normal

After update I started to get another problem with code which was working previously fine. It seems that now when I set a name for property for example like this:

      extern property_set Filter3DToneMapping ToneMapping
      {
       name = "Reinhard's tone mapping";
       state = QtnPropertyStateCollapsed;
      }

After toStr function I get following lines in the config file:

     Reinhard's tone mapping.Enable Reinhard tone mapping. = True
     Reinhard's tone mapping.Delta = 1
     Reinhard's tone mapping.Scale = 0.5
     Reinhard's tone mapping.Max. white = 1
     Reinhard's tone mapping.Gamma = 0.6
     Reinhard's tone mapping.Weight = 0.8

and run-time errors:
`Ambiguous property path:  "Reinhard's tone mapping.Enable Reinhard tone mapping. "` 

Before update it was working fine for me, and I got "ToneMapping" in saved file instead of "Reinhard's tone mapping". For me both problems are connected. Thanks for help in advance.

**Comment by lexxmark** [comment]
Hi Krzysztof,

Sorry for delay.

Could you please push your changes in master or (better) in some branch. So I will have possibility to debug code.
Also please send me AB_INI file that caused the parsing error.

I've fixed toStr function. Now it saves cppName of the property, not "display" name. Please update your submodule.

Thank you for cooperation.

**Comment by kmkolasinski** [comment]
Hi Alex,
thanks for feedback, I wanted to try your new commit yesterday but they have some maintenance works on github server, so I will try to do it today. 
if it will not work, I will commit my code and send you config file.

**Comment by kmkolasinski** [comment]
Hi, I've checked the latest commit and now save str function works fine but it seems that during loading it still uses  "names" instead of property name, because I have errors:

> "Cannot convert property Enable DOF<QtnPropertyBool> from string " True""
> "Cannot convert property Enable Reinhard tone mapping.<QtnPropertyBool> from string " True""

but in the saved file I have: 
```
DOF.EnableEffect = True
ToneMapping.EnableEffect = True
```
To summarize 
```
abSettings->toStr(data); // works fine, line 1971 in mainwindow.cpp
abSettings->fromStr(data); // does not work :(, line 2101 in mainwindow.cpp
```

Here is the config file which does not want to load: [config.ini](https://github.com/kmkolasinski/AwesomeBump/blob/master/Wiki/Tests/config.ini), I've pushed recent changes. Thanks in advance.

**Comment by lexxmark** [comment]
It seems like there were false errors. Actually the strings were parsed but function returned false because value was the same and property didn't change. I've fixed it. Please check.

In regards config.ini - I changed debug message, please try to load again and give me debug output.
I will try to debug it under Windows.

**Comment by kmkolasinski** [comment]
Hi, thank you for looking at this problem for me. I leave this sunday for a conference and I will back next week, so if I will have no time tomorrow or today I will be able to check it next week unfortunately. Anyway I will give you a feedback.

**Comment by kmkolasinski** [comment]
Hi, after update I have asserts which stop program. After message:

> "Cannot convert property FocalDepth<QtnPropertyFloat> from string " 10""

Program exit on assert:

> ASSERT: "false" in file /media/DANE/Doktorat/ZaawansowanaGrafika3D/AwesomeBumpRepo/AwesomeBump/Sources/utils/QtnProperty/Core/PropertySet.cpp, line 382

Do you know where could be a problem? I have no idea even where to look for it in your project :/
I will be able to check the code next week.

**Comment by lexxmark** [comment]
Thank you for feedback.
Definitely you can see that problem at "/media/DANE/Doktorat/ZaawansowanaGrafika3D/AwesomeBumpRepo/AwesomeBump/Sources/utils/QtnProperty/Core/PropertySet.cpp, line 382". You can set breakpoint there and debug the code.

Log message says that program tries to parse string ( 10") which is incorrect. It has quote char " at the end. I will look into it today or tomorrow.

Please send text file which you tried to load, because I didn't find FocalDepth in config.ini

**Comment by kmkolasinski** [comment]
Hi thanks, the FocalDepth is in another QtnProperty set responsible for 3D rendering: it is in the Bin/Conifg/settings3D.dat file. The content of this file is following:

```
DOF.EnableEffect = True
DOF.FocalLength = 25
DOF.FocalDepth = 10
DOF.FocalStop = 140
DOF.NoSamples = 4
DOF.NoRings = 7
DOF.Noise = False
DOF.Coc = 0.03
DOF.Threshold = 0.25
DOF.Gain = 1
DOF.BokehBias = 0.25
DOF.BokehFringe = 0.7
DOF.DitherAmount = 0.0001
Bloom.EnableEffect = True
Bloom.WeightA = 0.25
Bloom.WeightB = 0.25
Bloom.WeightC = 0.25
Bloom.WeightD = 0.25
Bloom.Vignette = 0.4
Bloom.VignetteAtt = 0.8
Flares.EnableEffect = True
Flares.NoSamples = 8
Flares.Dispersal = 0.25
Flares.HaloWidth = 0.5
Flares.Distortion = 1
Flares.weightLF = 10
ToneMapping.EnableEffect = True
ToneMapping.Delta = 1
ToneMapping.Scale = 0.5
ToneMapping.LumMaxWhite = 1
ToneMapping.GammaCorrection = 0.6
ToneMapping.BlendingWeight = 0.8
ParsedShader.MaxParams = 20
ParsedShader.LastShaderIndex = 0
ParsedShader.fParam1 = 0
ParsedShader.fParam2 = 0.4
ParsedShader.fParam3 = 3
ParsedShader.fParam4 = 50
ParsedShader.fParam5 = 50
ParsedShader.fParam6 = 50
ParsedShader.fParam7 = 50
ParsedShader.fParam8 = 50
ParsedShader.fParam9 = 50
ParsedShader.fParam10 = 50
ParsedShader.fParam11 = 50
ParsedShader.fParam12 = 50
ParsedShader.fParam13 = 50
ParsedShader.fParam14 = 50
ParsedShader.fParam15 = 50
ParsedShader.fParam16 = 50
ParsedShader.fParam17 = 50
ParsedShader.fParam18 = 50
ParsedShader.fParam19 = 50
ParsedShader.fParam20 = 50
```
This file is used in Dialog3DGeneralSettings.cpp file in Source/properties folder. I understand that the problem is during file parsing, but it was working few commits ago.

**Comment by lexxmark** [comment]
I've found an error in my code and an error in your code.
1. Please fix mainwindow.cpp line 2100:
```
stream >> data; // should be: data = stream.readAll();
```
2. There is some problems with PEG property generator. I only updated PEG.exe for windows. May I ask you or @ppiecuch to build QtnPropery project and update PEG tool for linux and OSX and I merge them into master.

After these fixes I will look for another possible mistakes.

**Comment by lexxmark** [comment]
I decided to rollback my recent modifications.
Now we have name and displayName in base property class.
So to change name in *.pef file use this line:
```
    displayName = "Reinhard's tone mapping";
```
instead of:
```
    name = "Reinhard's tone mapping";
```
I hope this helps to fix all issues.

**Comment by kmkolasinski** [comment]
Hi, thanks for feedback, so it means that I have to change all the "name" to displayName in pef files?
Additionally I have linker error to setCppName, after pulling you recent code:
```
 `QtnPropertySetFilter3DDOF::init()':AwesomeBump/Sources/properties/Filter3DDOF.peg.cpp:142: undefined reference to `QtnPropertyBase::setCppName(QString const&)'
```

**Comment by lexxmark** [comment]
Hi, thank you for your cooperation.

> so it means that I have to change all the "name" to displayName in pef files?

yes exactly. let's use "displayName" attribute to change property name in GUI.

> I have linker error to setCppName, after pulling you recent code:

I removed setCppName function from QtnPropertyBase class. You should got compile error not linker error. Also PEG should produce code that use setName instead setCppName. If it's not please rebuild PEG tool and try regenerate *.pef files. And send me PEG executable for your OS (linux I guess) so I will update PEG in QtnProperty master.

**Comment by kmkolasinski** [comment]
Ok, you were right, after cleaning both projects now it compiles. I still have some assert on start but it seems it is related to old property naming. 
I will debug it tomorrow and thanks for help. I will send you also the executables.

**Comment by kmkolasinski** [comment]
Hi, after compilation and substitution of all name to displayName I have the same error as few weeks ago:
```
"Cannot convert property FocalDepth<QtnPropertyFloat> from string " 10""
```
The config file bin/settings3D.dat has following lines:
```
DOF.EnableEffect = False
DOF.FocalLength = 25
DOF.FocalDepth = 10
DOF.FocalStop = 140
...
```
 Strange that `DOF.EnableEffect ` and `DOF.FocalLength` are parsed without errors but  program crashed on: `DOF.FocalDepth ` with assert:
```
ASSERT: "false" in file AwesomeBump/Sources/utils/QtnProperty/Core/PropertySet.cpp, line 382
```

**Comment by kmkolasinski** [comment]
Ok, I found that this is related to state of property. Setting state as
```
state = QtnPropertyStateInvisible
```
leads to assert as above, hence invisible properties lead to crash...
I would like to have few invisible for users properties, is there any way to solve this problem?

**Comment by lexxmark** [comment]
Thank you very much.
Your last message gave me a clue where to find an error.
I've fixed the code, please check now.

**Comment by kmkolasinski** [comment]
Hi, thanks for info, today I'm leaving for weekend, so I will be able to check it on monday.

**Comment by kmkolasinski** [comment]
Hi, so now program runs and I can save or load properties to txt file. However it works only with 3D settings, the main config.ini file still does not want to load, but I can save it. I don't understand why. For example the lines:
```
    QFile file( QString(AB_INI) );
    if( !file.open( QIODevice::ReadOnly ) )
         return;

    QTextStream stream(&file);
    QString data;
    data = stream.readAll();
    abSettings->fromStr(data);

    QString tmpStr;
    abSettings->Diffuse.toStr(tmpStr);

    qDebug()  << tmpStr;
    qDebug()  << abSettings->Diffuse.Basic.GrayScale.EnableGrayScale.value();
    qDebug()  << abSettings->presetName.value();

```
Few remarks, which may help you localize where is the problem:
* "data" - contains proper values,
* `qDebug() << tmpStr;` does not print proper values, just the default ones.
* `qDebug() << abSettings->Diffuse.Basic.GrayScale.EnableGrayScale.value(); `// does not print the value which is in the config.ini file.
*  `qDebug()  << abSettings->presetName.value();` // prints proper value...

abSettings is an object of:
```
property_set AwesomeBump
{
    QString presetName{
        value = "Default";
    }
    extern property_set FormImageProp Diffuse;
   ....
}
```
So it seems that this is related to fact that `Diffuse` is a subproperty field  `extern property_set FormImageProp Diffuse` .
Another clue which may be important, the `abSettings` object is never displayed in GUI, I used it as a properties container for all settings.

**Comment by lexxmark** [comment]
Now invisible and immutable properties don't load from text. I relax condition: only immutable properties don't load from text.
Hope this helps.

**Comment by kmkolasinski** [comment]
Thanks for help and I am really sorry, but I am a terrible user :( I still have problems, but this time something else. I have an enum field:
```
enum COLOR_FILTER_METHOD
{
    Angle1(1, "Angle based #1"),
    Angle2(2, "Angle based #2"),
    Distance(3, "Distance based")
}
```
For some reason toStr function saves it as:
```
Diffuse.RMFilter.ColorFilter.Method = COLOR_FILTER_METHOD::Distance based
```
instead of (which I would expect)
```
Diffuse.RMFilter.ColorFilter.Method = COLOR_FILTER_METHOD::Distance
```
then it crashes in fromStr function, with assert
```
"Cannot convert property Method<QtnPropertyEnum> from string " COLOR_FILTER_METHOD::Distance based""
```
I tried to change the config.ini file and set:
```
Diffuse.RMFilter.ColorFilter.Method = COLOR_FILTER_METHOD::Distance
```
But, I got the same error:
```
"Cannot convert property Method<QtnPropertyEnum> from string " COLOR_FILTER_METHOD::Distance""
```

**Comment by lexxmark** [comment]
Hi,
```
Thanks for help and I am really sorry, but I am a terrible user :( I still have problems, but this time something else. I have an enum field:
```
It's OK. Thank you because you make my project better.
I will look into this.

**Comment by lexxmark** [comment]
I've fixed enums. Now enum item have displayName string.
Please update QtnProperty project. Note that you should rebuld PEG tool.
Now you should get:
```
Diffuse.RMFilter.ColorFilter.Method = COLOR_FILTER_METHOD::Distance
```
Also, please, send me updated PEG for linux.

**Comment by kmkolasinski** [comment]
Thanks! It seems it works, however I would like to work a little bit with the code to see it will definitely work. Then I will send you PEG file, otherwise it may occur that there are still some problems.
